# Generated by Django 3.0.7 on 2020-08-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Question_approval', models.BooleanField(default=False)),
                ('Question_title', models.CharField(max_length=150)),
                ('Question_discription', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_id', models.CharField(max_length=20)),
                ('Subject_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Topictag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic_id', models.CharField(max_length=25)),
                ('Topic_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('Mobile', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Question')),
                ('Topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Topictag')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Subject'),
        ),
    ]
