# Generated by Django 3.0.7 on 2020-08-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Question_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
