# Generated by Django 2.2.7 on 2020-12-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.ImageField(default='', upload_to='author_image/'),
        ),
    ]
